### ISSUE TITLE
when I run I get this error

### ISSUE THREAD

**Issue by Austin-ag** [lucien2k/sonoff-python#4]
ModuleNotFoundError: No module named 'requests

running python 3.7.3

**Comment by kutzowsky** [comment]
`pip install requests` should resolve your problem for now. You'll probably need `websocket-client` module as well. 

The issue with not downloading dependencies during `pip install` was fixed in #2, but an older version is on the pypi. @lucien2k could you publish a new one?

**Comment by lucien2k** [comment]
Should be fixed with the new release
