### ISSUE TITLE
AttributeError: Sonoff instance has no attribute 'get_api_region'

### ISSUE THREAD

**Issue by ridderr** [lucien2k/sonoff-python#9]
Create work. 
Had also to install:

- sudo pip install websocket
- sudo pip install requests
- sudo pip install websocket-client

Now i'm getting an error: AttributeError: Sonoff instance has no attribute 'get_api_region'
Since these 3 lines are not relevant I have removed them.

**Comment by PipeManMusic** [comment]
Same Error here.
